import { COLORS } from "../theme";

export const cardStyles = {
  highlightCard: {
    background: COLORS.surface,
    border: `1px solid ${COLORS.border}`,
    borderRadius: 10,
    padding: "20px 20px",
  },
  highlightIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 8,
    background: COLORS.blueDim,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 14,
  },
  highlightTitle: {
    fontFamily: "'Space Grotesk', sans-serif",
    fontWeight: 600,
    fontSize: 15,
    color: COLORS.text,
    marginBottom: 6,
  },
  highlightDesc: {
    fontFamily: "'Inter', sans-serif",
    fontSize: 13,
    color: COLORS.textMuted,
    lineHeight: 1.5,
  },
  tag: {
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: 11,
    color: COLORS.cyan,
    background: "rgba(57,217,217,0.08)",
    border: "1px solid rgba(57,217,217,0.25)",
    borderRadius: 4,
    padding: "3px 8px",
  },
  thumbSvg: {
    display: "block",
  },
  projectCard: {
    background: COLORS.surface,
    border: `1px solid ${COLORS.border}`,
    borderRadius: 10,
    overflow: "hidden",
  },
  projectBody: {
    padding: "16px 18px",
  },
  projectTitle: {
    fontFamily: "'Space Grotesk', sans-serif",
    fontWeight: 600,
    fontSize: 15,
    color: COLORS.text,
    marginBottom: 6,
  },
  projectDesc: {
    fontFamily: "'Inter', sans-serif",
    fontSize: 13,
    color: COLORS.textMuted,
    lineHeight: 1.5,
    marginBottom: 14,
  },
  tagsRow: {
    display: "flex",
    gap: 6,
    flexWrap: "wrap",
    marginBottom: 14,
  },
  inlineLinkButton: {
    fontFamily: "'Inter', sans-serif",
    fontSize: 13,
    fontWeight: 500,
    color: COLORS.blue,
    textDecoration: "none",
    background: "transparent",
    border: "none",
    padding: 0,
    cursor: "pointer",
  },
  blogCard: {
    background: COLORS.surface,
    border: `1px solid ${COLORS.border}`,
    borderRadius: 10,
    overflow: "hidden",
  },
  blogBody: {
    padding: "16px 18px",
  },
  blogTitle: {
    fontFamily: "'Space Grotesk', sans-serif",
    fontWeight: 600,
    fontSize: 15,
    color: COLORS.text,
    marginBottom: 6,
  },
  blogExcerpt: {
    fontFamily: "'Inter', sans-serif",
    fontSize: 13,
    color: COLORS.textMuted,
    lineHeight: 1.5,
    marginBottom: 10,
  },
  blogMeta: {
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: 11,
    color: COLORS.textFaint,
  },
  sectionHeader: {
    display: "flex",
    alignItems: "baseline",
    justifyContent: "space-between",
    marginBottom: 22,
  },
  sectionTitle: {
    fontFamily: "'Space Grotesk', sans-serif",
    fontWeight: 600,
    fontSize: 22,
    color: COLORS.text,
    margin: 0,
  },
};
