import { COLORS } from "../theme";

export const aboutStyles = {
  heroSection: {
    display: "flex",
    gap: 48,
    padding: "56px 48px 40px",
    flexWrap: "wrap",
    alignItems: "flex-start",
  },
  heroContent: {
    maxWidth: 480,
    flex: "1 1 380px",
  },
  sectionAccent: {
    width: 40,
    height: 4,
    background: COLORS.blue,
    borderRadius: 2,
    marginBottom: 18,
  },
  heading: {
    fontFamily: "'Space Grotesk', sans-serif",
    fontWeight: 700,
    fontSize: 34,
    color: COLORS.text,
    margin: "0 0 18px",
  },
  paragraph: {
    fontFamily: "'Inter', sans-serif",
    fontSize: 15,
    color: COLORS.textMuted,
    lineHeight: 1.7,
    marginBottom: 32,
  },
  infoGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 24,
    marginBottom: 8,
  },
  uploadRow: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    marginTop: 20,
  },
  uploadButton: {
    fontFamily: "'Inter', sans-serif",
    fontSize: 13,
    fontWeight: 500,
    color: COLORS.text,
    background: "transparent",
    border: `1px solid ${COLORS.borderStrong}`,
    borderRadius: 7,
    padding: "8px 14px",
    cursor: "pointer",
  },
  uploadHint: {
    fontFamily: "'Inter', sans-serif",
    fontSize: 12,
    color: COLORS.textFaint,
  },
  hiddenFileInput: {
    display: "none",
  },
  avatarWrap: {
    width: 240,
    height: 240,
    borderRadius: 16,
    overflow: "hidden",
    flexShrink: 0,
  },
  infoRow: {
    display: "flex",
    alignItems: "flex-start",
    gap: 12,
  },
  infoIconWrap: {
    width: 30,
    height: 30,
    borderRadius: 7,
    background: COLORS.blueDim,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  infoLabel: {
    fontFamily: "'Inter', sans-serif",
    fontSize: 12,
    color: COLORS.textFaint,
  },
  infoValue: {
    fontFamily: "'Inter', sans-serif",
    fontSize: 14,
    color: COLORS.text,
    fontWeight: 500,
    whiteSpace: "nowrap",
  },
  infoLink: {
    fontFamily: "'Inter', sans-serif",
    fontSize: 14,
    color: COLORS.blue,
    fontWeight: 500,
    textDecoration: "none",
    whiteSpace: "nowrap",
  },
  skillsSection: {
    padding: "8px 48px 64px",
  },
  skillsHeading: {
    fontFamily: "'Space Grotesk', sans-serif",
    fontWeight: 600,
    fontSize: 20,
    color: COLORS.text,
    marginBottom: 28,
  },
  skillsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(96px, 1fr))",
    gap: 14,
  },
  softSkillsHeading: {
    fontFamily: "'Space Grotesk', sans-serif",
    fontWeight: 600,
    fontSize: 18,
    color: COLORS.text,
    margin: "28px 0 16px",
  },
  softSkillsRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: 12,
  },
  softSkillChip: {
    fontFamily: "'Inter', sans-serif",
    fontSize: 13,
    color: COLORS.text,
    background: COLORS.surface,
    border: `1px solid ${COLORS.border}`,
    borderRadius: 999,
    padding: "10px 14px",
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
  },
  skillTile: {
    background: COLORS.surface,
    border: `1px solid ${COLORS.border}`,
    borderRadius: 10,
    padding: "16px 10px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 10,
  },
  skillIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 8,
    background: COLORS.surfaceAlt,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  skillLabel: {
    fontFamily: "'Inter', sans-serif",
    fontSize: 12,
    color: COLORS.textMuted,
  },
};
